

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Test!@#1234"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - beststore_network
    volumes:
      - sql_data:/var/opt/mssql

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: beststore
    ports:
      - "90:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=BestStoreMVC;User Id=sa;Password=Test!@#1234;MultipleActiveResultSets=true;TrustServerCertificate=True
    depends_on:
      - sqlserver
    networks:
      - beststore_network

volumes:
  sql_data:

networks:
  beststore_network:
